import { Activity, CheckCircle2 } from "lucide-react";

import { ModelComparisonChart } from "@/components/charts/ModelComparisonChart";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getDashboardData } from "@/lib/data";
import { formatPct, formatScore } from "@/lib/formatters";

export default async function DiagnosticsPage() {
  const data = await getDashboardData();

  return (
    <DashboardShell manifest={data.manifest}>
      <div className="space-y-6">
        <section>
          <Badge variant="success">
            <Activity className="mr-1 h-3 w-3" />
            Diagnostics
          </Badge>
          <h1 className="mt-4 text-3xl font-semibold text-white">Model Health Diagnostics</h1>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">
            Stability, validation, and monitoring summaries for production-readiness review.
          </p>
        </section>

        <div className="grid gap-5 lg:grid-cols-3">
          {data.leaderboard.slice(0, 3).map((row) => (
            <Card key={row.model}>
              <CardContent className="p-5">
                <div className="flex items-center justify-between gap-3">
                  <p className="font-semibold text-white">{row.model}</p>
                  <Badge variant={row.recommended ? "success" : "muted"}>#{row.rank}</Badge>
                </div>
                <div className="mt-5 grid grid-cols-2 gap-3">
                  <Metric label="Stability" value={formatScore(row.stability)} />
                  <Metric label="MAPE" value={formatPct(row.mape)} />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-emerald-300" />
                Cross-Validation Summary
              </CardTitle>
              <CardDescription>Walk-forward validation metrics exported by the Python pipeline.</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Model</TableHead>
                    <TableHead>MAPE</TableHead>
                    <TableHead>Std</TableHead>
                    <TableHead>Folds</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.cvSummary.map((row) => (
                    <TableRow key={row.model}>
                      <TableCell className="font-medium text-white">{row.model}</TableCell>
                      <TableCell>{formatPct(row.cv_mape_mean)}</TableCell>
                      <TableCell>{formatPct(row.cv_mape_std)}</TableCell>
                      <TableCell>{row.folds ?? "-"}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <ModelComparisonChart rows={data.leaderboard} metric="composite_score" title="Model Health Score" />
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Residual Diagnostics Status</CardTitle>
            <CardDescription>Residual plots and statistical tests remain generated by the Python reporting layer.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-3 md:grid-cols-4">
            {["ADF", "Shapiro-Wilk", "Jarque-Bera", "Ljung-Box"].map((test) => (
              <div key={test} className="rounded-md border border-slate-700/70 bg-slate-950/45 p-4">
                <p className="text-xs uppercase tracking-wide text-slate-500">{test}</p>
                <p className="mt-2 text-sm text-slate-300">Available in Python reports</p>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </DashboardShell>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-slate-700/70 bg-slate-950/45 p-3">
      <p className="text-xs uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-1 text-lg font-semibold text-white">{value}</p>
    </div>
  );
}

